---
- name: Update and upgrade Ubuntu server
  hosts: ubuntu_servers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Autoremove unused packages
      apt:
        autoremove: yes

    - name: Clean up apt cache
      apt:
        autoclean: yes
