---
- name: Update and upgrade Ubuntu server
  hosts: ubuntu_servers
  become: yes # Habilita escalado de privilegios
  become_method: sudo # Usa 'sudo' para el escalado (esto es el predeterminado, pero se puede especificar explícitamente)

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Autoremove unused packages
      apt:
        autoremove: yes

    - name: Clean up apt cache
      apt:
        autoclean: yes
